Controllers/BookController.cs
using Library.Abstractions;
using Library.Models;
using Library.Models.Books;
using Library.Models.Readers;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Library.Controllers
{
    public class BookController : Controller
    {
        private readonly BookManager _bookManager;
        private readonly AuthorManager _authorManager;

        public BookController(BookManager bookManager, AuthorManager authorManager)
        {
            _bookManager = bookManager;
            _authorManager = authorManager;
        }
        public IActionResult Index()
        {

            return View();
        }

        [HttpGet]
        public async Task<IActionResult> AddBook()

        {   var authors = await _authorManager.GetAllAuthorsAsync(false);
            ViewBag.Authors = new SelectList(authors, "Id", "FullName");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddBook(Book book, string authorId, string bookShelfId, CoverColor coverColor,int numberOfPages=0)
        {
            await _bookManager.AddBookAsync(book, int.Parse(authorId), bookShelfId, coverColor, numberOfPages);

            //Author newAuthor = new Author { Name = authorName };
            //Book Book1 = new Book { Name = book.Name, Author = newAuthor, Publication = book.Publication, BookCase = bookCase, CoverPath = GetCoverColor(coverColor) };
            //db.Authors.Add(newAuthor);
            //db.Books.Add(Book1);

            return RedirectToAction("ShowAllBooks");
        }
        public async Task<IActionResult> ShowAllBooks(string name, int author = 0, int page = 1, SortState sortOrder = SortState.NameAsc, int bookShelfId = 0)
        {
            var viewModel = await _bookManager.GetAllBooksAsync(name, author, page, sortOrder, bookShelfId);

            return View(viewModel);
        }
        public async Task<IActionResult> DeleteBook(int id)
        {
            await _bookManager.DeleteBookAsync(id);

            return RedirectToAction("ShowAllBooks");
        }
        public async Task<IActionResult> ShowBook(int bookId, bool includeReader = false)
        {
            if (includeReader)
            {
                var bookWithReader = await _bookManager.GetBookWithReaderAsync(bookId);
                if (bookWithReader != null) return View(bookWithReader);
            }
            else
            {
                var book = await _bookManager.GetBookWithReaderAsync(bookId);
                if (book != null) return View(book);
            }
            return NotFound();
        }


    }
}

Controllers/ReaderController.cs
using Library.Abstractions;
using Library.Models;
using Library.Models.Account;
using Library.Models.Books;
using Library.Models.Readers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;

namespace Library.Controllers
{

    public class ReaderController : Controller
    {
        private readonly ReaderManager _readerManager;
        private readonly BookManager _bookManager;
        private readonly DataManager _dataManager;


        public ReaderController(ReaderManager readerManager, BookManager bookManager, DataManager dataManager)
        {
            _readerManager = readerManager;
            _bookManager = bookManager;
            _dataManager = dataManager;
        }


        public async Task<IActionResult> AddBookToReader(int readerId, int bookId)
        {

            var result = await _dataManager.BookToReaderAsync(readerId, bookId);
            if (result ==null)
            {
                return Content("Error");
            }
            return RedirectToAction("Index");

        }
        public async Task<IActionResult> AddBookToLibrary(int readerId, int bookId)
        {

            var result = await _dataManager.BookToLibraryAsync(readerId, bookId);
            if (result == null)
            {
                return Content("Error");
            }
            return RedirectToAction("Index");

        }

        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> AddBookToReaderByAdmin()
        {
            var readers = await _readerManager.GetAllReadersAsync(false);
            var allBooks = await _bookManager.GetListOfBooksAsync();
            var freeBooks = allBooks.Where(x => !x.IsPicked).ToList();
            ViewBag.Readers = new SelectList(readers, "Id", "FullName");
            ViewBag.Books = new SelectList(freeBooks, "Id", "Name");
            return View();
        }

        public async Task<IActionResult> Index()
        {
            var ReaderList = await _readerManager.GetAllReadersAsync();
            return View(ReaderList);
        }
        public async Task<IActionResult> DeleteReader(int id)
        {
            await _readerManager.DeleteReaderAsync(id);
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> ShowReader(int readerId)
        {
            var reader = await _readerManager.GetReaderAsync(readerId);
            if (reader != null) return View(reader);
            return Content("Error");
        }
    }
}

Views/Shared/_Layout.cshtml
@using System.Security.Claims;
@{
    var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
    var adminRole = User.IsInRole("Administrator");
    var userRole = User.IsInRole("User");

}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta content="Library" name="description" />
    <!-- App favicon -->
    <link rel="shortcut icon" href="images/favicon.ico">

    <link href="/html/saas/assets/css/vendor/jquery-jvectormap-1.2.2.css" rel="stylesheet" type="text/css" />
    <link href="/html/saas/assets/css/icons.min.css" rel="stylesheet" type="text/css" />
    <link href="/html/saas/assets/css/app.min.css" rel="stylesheet" type="text/css" id="light-style" />

    <title>Library</title>

</head>
<body>
    <div class="wrapper">
        <div class="leftside-menu" style="background: #000">
            <!-- LOGO -->
            <a href="/Home/StartPage" class="logo text-center logo-light">
                <span class="logo-lg">
                    <img src="/images/bibli.png" alt="" height="50">
                </span>
            </a>
            <!--Leftside Menu-->
            <div class="h-100" id="leftside-menu-container">

                <ul class="side-nav">
                    <li class="side-nav-title side-nav-item" style="color: white">Menu</li>
                    <!-- Books -->
                    <li class="side-nav-item">
                        <a data-bs-toggle="collapse" href="#sidebarBooks" aria-expanded="false" aria-controls="sidebarDashboards" class="side-nav-link">
                            <span style="color:white"> Книги </span>
                        </a>
                        <div class="collapse" id="sidebarBooks">
                            <ul class="side-nav-second-level">
                                <li>
                                    <a asp-controller="Book" asp-action="ShowAllBooks"><span style="color:white">Список всех книг</span></a>
                                </li>
                                <li>
                                    <a asp-controller="Book" asp-action="AddBook"><span style="color:white">Добавить новую книгу</span></a>
                                </li>
                            </ul>
                        </div>
                    </li>
                    @if (adminRole)
                    {
                        <!-- Readers -->
                        <li class="side-nav-item">
                            <a data-bs-toggle="collapse" href="#sidebarReaders" aria-expanded="false" aria-controls="sidebarDashboards" class="side-nav-link">
                                <i class="uil-home-alt"></i>
                                <span style="color:white"> Читатели </span>
                            </a>
                            <div class="collapse" id="sidebarReaders">
                                <ul class="side-nav-second-level">
                                    <li>
                                        <a asp-controller="Reader" asp-action="Index"><span style="color:white">Показать читателей</span></a>
                                    </li>
                                    <li>
                                        <a asp-controller="Reader" asp-action="AddBookToReaderByAdmin"><span style="color:white">Добавить книгу читателю</span></a>
                                    </li>

                                </ul>
                            </div>
                        </li>
                    }
                </ul>
            </div>
        </div>
        <div class="content-page">
            <div class="content">
                <!-- Topbar Start -->
                <div class="navbar-custom">
                    <ul class="list-unstyled topbar-menu float-end mb-0">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="dropdown notification-list">
                                <a class="nav-link dropdown-toggle nav-user arrow-none me-0" data-bs-toggle="dropdown" role="button" aria-haspopup="false"
                                   aria-expanded="false">
                                    <span class="account-user-avatar">
                                        <img src="/images/Avatar.jpeg" alt="user-image" class="rounded-circle">
                                    </span>
                                    <span>
                                        <span class="account-user-name">@User.Identity.Name</span>
                                        <span class="account-position">Role Layout 88</span>
                                    </span>
                                </a>
                                <div class="dropdown-menu dropdown-menu-end dropdown-menu-animated topbar-dropdown-menu profile-dropdown">
                                    

                                        <!-- item-->
                                        <a asp-action="ShowReader" asp-controller="User" asp-route-userId="@userId" class="dropdown-item notify-item">
                                            <i class="mdi mdi-account-circle me-1"></i>
                                            <span>Профиль</span>
                                        </a>

                                        <form method="post" asp-action="Logout" asp-controller="Account">
                                        <input type="submit" value="Выйти" class="dropdown-item notify-item">
                                        </form>
                                        @* <a asp-action="Logout" asp-controller="Account" class="dropdown-item notify-item">
                                            <i class="mdi mdi-logout me-1"></i>
                                            <span>Выйти</span>
                                        </a> *@
                                    
                                </div>
                            </li>
                        }
                        else
                        {
                            <a asp-controller="Account" asp-action="Register" class="text-muted ms-1">Зарегистрироваться</a>
                            <a asp-controller="Account" asp-action="Login" class="text-muted ms-1">Войти</a>
                        }
                    </ul>
                    <button class="button-menu-mobile open-left">
                        <i class="mdi mdi-menu"></i>
                    </button>

                </div>
                <!-- end Topbar -->
                <div class="container-fluid">
                    @RenderBody()
                </div>
            </div>
        </div>
    </div>





    <script src="/html/saas/assets/js/vendor.js"></script>
    <script src="/html/saas/assets/js/app.js"></script>

    <!-- third party js -->
    <script src="/html/saas/assets/js/vendor/apexcharts.min.js"></script>
    <script src="/html/saas/assets/js/vendor/jquery-jvectormap-1.2.2.min.js"></script>
    <script src="/html/saas/assets/js/vendor/jquery-jvectormap-world-mill-en.js"></script>
    <!-- third party js ends -->
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>