Models/Books/Book.cs
using Library.Models.Authors;
using Library.Models.Readers;

namespace Library.Models.Books
{
    public class Book
    {
        public int Id { get; set; }
        public string? Name { get; set; }
        public int Publication { get; set; }

        public int? AuthorId { get; set; }
        public Author Author { get; set; }

        public int? ReaderId { get; set; }
        public Reader Reader { get; set; }

        public int? BookCaseId { get; set; }
        public BookCase BookCase { get; set; }

        public int PageCount { get; set; }
        public int NumberOfReading { get; set; } = 0;

        public bool IsPicked { get; set; } = false;
        public string? CoverPath { get; set; } = null;

    }
}

Models/Books/BookCase.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace Library.Models.Books
{
    public class BookCase
    {
        public int Id { get; set; }
        public int row { get; set; } = 1;
        public int column { get; set; } = 1;
        public string? BookName { get; set; }

        public bool IsEmpty { get; set; } = true;

        public int? BookShelfId { get; set; }
        public BookShelf BookShelf { get; set; }
    }
}

Models/Books/Bookshelf.cs
namespace Library.Models.Books
{
    public class BookShelf
    {
        public int Id { get; set; }
        public int OccupiedСells { get; set; } = 0;
    }
}

Models/Books/CoverColor.cs
namespace Library.Models.Books
{
    public enum CoverColor
    {
        Red,
        Green,
        Blue
    }
}

Models/Books/FilterViewModel.cs
using Library.Models.Authors;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Library.Models.Books
{
    public class FilterViewModel
    {
        public SelectList Authors { get; set; }
        public int SelectedAuthor { get; set; }
        public string SelectedName { get; set; }
        public int SelectedBookShelf { get; set; }

        public FilterViewModel(List<Author> authors, int author, string name, int selectedBookShelf)
        {
            authors.Insert(0, new Author { FirstName = "Any", Id = 0 });
            Authors = new SelectList(authors, "Id", "FullName", author);
            SelectedAuthor = author;
            SelectedName = name;
            SelectedBookShelf = selectedBookShelf;
        }
    }
}

Models/Books/IndexViewModel.cs
namespace Library.Models.Books
{
    public class IndexViewModel
    {
        public IEnumerable<BookShelf> Bookshelf { get; set; }
        public IEnumerable<Book> Books { get; set; }
        public PageViewModel PageViewModel { get; set; }
        public SortViewModel SortViewModel { get; set; }
        public FilterViewModel FilterViewModel { get; set; }

        public IndexViewModel(IEnumerable<Book> books, PageViewModel pageViewModel,
            FilterViewModel filterViewModel, SortViewModel sortViewModel)
        {
            Books = books;
            FilterViewModel = filterViewModel;
            SortViewModel = sortViewModel;
            PageViewModel = pageViewModel;
        }
    }
}

Models/Books/PageViewModel.cs
namespace Library.Models.Books
{
    public class PageViewModel
    {
        public int PageNumber { get; set; }
        public int TotalPages { get; set; }
        public bool HasPreviousPage => PageNumber > 1;
        public bool HasNextPage => PageNumber < TotalPages;

        public PageViewModel(int count, int pageNumber, int pageSize)
        {
            PageNumber = pageNumber;
            TotalPages = (int)Math.Ceiling(count / (double)pageSize);
        }
    }
}

Models/Books/ShowBookViewModel.cs
namespace Library.Models.Books
{
    public class ShowBookViewModel
    {
    }
}

Models/Books/SortState.cs
namespace Library.Models.Books
{
    public enum SortState
    {
        NameAsc,
        NameDesc,
        PublicatinAsc,
        PublicatinDesc,
        AuthorAsc,
        AuthorDesc,
        BookShelfAsc,
        BookShelfDesc,
    }
}

Models/Books/SortViewModel.cs
namespace Library.Models.Books
{
    public class SortViewModel
    {
        public SortState NameSort { get; set; }
        public SortState PublicationSort { get; set; }
        public SortState AuthorSort { get; set; }
        public SortState BookShelfSort { get; set; }
        public SortState Current { get; set; }

        public SortViewModel(SortState sortOrder)
        {
            NameSort = sortOrder == SortState.NameAsc ? SortState.NameDesc : SortState.NameAsc;
            PublicationSort = sortOrder == SortState.PublicatinAsc ? SortState.PublicatinDesc : SortState.PublicatinAsc;
            AuthorSort = sortOrder == SortState.AuthorAsc ? SortState.AuthorDesc : SortState.AuthorAsc;
            BookShelfSort = sortOrder == SortState.BookShelfAsc ? SortState.BookShelfDesc : SortState.BookShelfAsc;
            Current = sortOrder;
        }
    }
}

Controllers/AuthorController.cs
using Library.Abstractions;
using Microsoft.AspNetCore.Mvc;

namespace Library.Controllers
{
    public class AuthorController : Controller
    {
        private readonly AuthorManager _authorManager;

        public AuthorController(AuthorManager authorManager)
        {
            _authorManager = authorManager;
        }

        [HttpGet]
        public IActionResult AddNewAuthor()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddNewAuthor(string firstName, string lastName, string? pseudonym)
        {
            _authorManager.AddAuthor(firstName, lastName, pseudonym);
            return RedirectToAction("AddBook", "Book");
        }
    }
}

Controllers/BookController.cs
using Library.Abstractions;
using Library.Models;
using Library.Models.Books;
using Library.Models.Readers;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Library.Controllers
{
    public class BookController : Controller
    {
        private readonly BookManager _bookManager;
        private readonly AuthorManager _authorManager;

        public BookController(BookManager bookManager, AuthorManager authorManager)
        {
            _bookManager = bookManager;
            _authorManager = authorManager;
        }
        public IActionResult Index()
        {

            return View();
        }

        [HttpGet]
        public async Task<IActionResult> AddBook()

        {   var authors = await _authorManager.GetAllAuthorsAsync(false);
            ViewBag.Authors = new SelectList(authors, "Id", "FullName");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddBook(Book book, string authorId, string bookShelfId, CoverColor coverColor,int numberOfPages=0)
        {
            await _bookManager.AddBookAsync(book, int.Parse(authorId), bookShelfId, coverColor, numberOfPages);

            //Author newAuthor = new Author { Name = authorName };
            //Book Book1 = new Book { Name = book.Name, Author = newAuthor, Publication = book.Publication, BookCase = bookCase, CoverPath = GetCoverColor(coverColor) };
            //db.Authors.Add(newAuthor);
            //db.Books.Add(Book1);

            return RedirectToAction("ShowAllBooks");
        }
        public async Task<IActionResult> ShowAllBooks(string name, int author = 0, int page = 1, SortState sortOrder = SortState.NameAsc, int bookShelfId = 0)
        {
            var viewModel = await _bookManager.GetAllBooksAsync(name, author, page, sortOrder, bookShelfId);

            return View(viewModel);
        }
        public async Task<IActionResult> DeleteBook(int id)
        {
            await _bookManager.DeleteBookAsync(id);

            return RedirectToAction("ShowAllBooks");
        }
        public async Task<IActionResult> ShowBook(int bookId, bool includeReader = false)
        {
            if (includeReader)
            {
                var bookWithReader = await _bookManager.GetBookWithReaderAsync(bookId);
                if (bookWithReader != null) return View(bookWithReader);
            }
            else
            {
                var book = await _bookManager.GetBookWithReaderAsync(bookId);
                if (book != null) return View(book);
            }
            return NotFound();
        }


    }
}

Controllers/ReaderController.cs
using Library.Abstractions;
using Library.Models;
using Library.Models.Account;
using Library.Models.Books;
using Library.Models.Readers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;

namespace Library.Controllers
{

    public class ReaderController : Controller
    {
        private readonly ReaderManager _readerManager;
        private readonly BookManager _bookManager;
        private readonly DataManager _dataManager;


        public ReaderController(ReaderManager readerManager, BookManager bookManager, DataManager dataManager)
        {
            _readerManager = readerManager;
            _bookManager = bookManager;
            _dataManager = dataManager;
        }


        public async Task<IActionResult> AddBookToReader(int readerId, int bookId)
        {

            var result = await _dataManager.BookToReaderAsync(readerId, bookId);
            if (result ==null)
            {
                return Content("Error");
            }
            return RedirectToAction("Index");

        }
        public async Task<IActionResult> AddBookToLibrary(int readerId, int bookId)
        {

            var result = await _dataManager.BookToLibraryAsync(readerId, bookId);
            if (result == null)
            {
                return Content("Error");
            }
            return RedirectToAction("Index");

        }

        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> AddBookToReaderByAdmin()
        {
            var readers = await _readerManager.GetAllReadersAsync(false);
            var allBooks = await _bookManager.GetListOfBooksAsync();
            var freeBooks = allBooks.Where(x => !x.IsPicked).ToList();
            ViewBag.Readers = new SelectList(readers, "Id", "FullName");
            ViewBag.Books = new SelectList(freeBooks, "Id", "Name");
            return View();
        }

        public async Task<IActionResult> Index()
        {
            var ReaderList = await _readerManager.GetAllReadersAsync();
            return View(ReaderList);
        }
        public async Task<IActionResult> DeleteReader(int id)
        {
            await _readerManager.DeleteReaderAsync(id);
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> ShowReader(int readerId)
        {
            var reader = await _readerManager.GetReaderAsync(readerId);
            if (reader != null) return View(reader);
            return Content("Error");
        }
    }
}

Views/Book/AddBook.cshtml
@using Library.Models.Books
@model Book
<h2>Add new book</h2>

<form method="post">
    <label>Название книги</label>
    <input type="text" name="name" /><br />

    <label>Автор</label>
    @Html.DropDownList("authorId",ViewBag.Authors as SelectList)
    <a asp-controller="Author" asp-action="AddNewAuthor">Добавить нового автора</a><br />

    <label>Дата публикации</label>
    <input type="number" name="publication" /><br />

    <label>Количество страниц</label>
    <input type="number" name="numberOfPages" /><br />

    <label>Цвет обложки</label>
    <select name="coverColor">
        <option value="@CoverColor.Red">Красная</option>
        <option value="@CoverColor.Blue">Синяя</option>
        <option value="@CoverColor.Green">Зеленая</option>
    </select>
    <label>Стеллаж</label>
    <select name="bookShelfId">
        <option value ="1">1</option>
        <option value ="2">2</option>
    </select><br>
    <input type="submit" value="Add" />
</form>

Views/Book/Index.cshtml
<h2>Library</h2>

@if (User.Identity.IsAuthenticated)
{
    <p>@User.Identity.Name</p>
    <form method="post" asp-controller="Account" asp-action="Logout">
        <input type="submit" value="Выход" />
    </form>
}

Views/Book/ShowBook.cshtml
@using System.Security.Claims;
@using Microsoft.AspNetCore.Identity;


@model Book
@{
    var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
    var adminRole = User.IsInRole("Administrator");
    var userRole = User.IsInRole("User");
    int readerId = 0;
    if (userId != null)
    {

        readerId = int.Parse(@User.Claims.Where(x => x?.Type == "readerId").Select(x => x?.Value).FirstOrDefault());
    }

}

<body class="loading">
    <!-- Begin page -->
    <div class="wrapper">

        <!-- ============================================================== -->
        <!-- Start Page Content here -->
        <!-- ============================================================== -->


        <div class="content">
            <!-- Start Content-->
            <div class="container-fluid">

                <!-- start page title -->
                <div class="row">
                    <div class="col-12">
                        <div class="page-title-box">
                            <h4 class="page-title">Product Details</h4>
                        </div>
                    </div>
                </div>
                <!-- end page title -->

                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-lg-5">
                                        <!-- Product image -->
                                        <a href="javascript: void(0);" class="text-center d-block mb-4">
                                            <img src="@Model.CoverPath" class="img-fluid" style="max-width: 280px;" alt="Book-img" />
                                        </a>
                                        @* <div class="d-lg-flex d-none justify-content-center">
                                        <a href="javascript: void(0);">
                                        <img src="assets/images/products/product-1.jpg" class="img-fluid img-thumbnail p-2" style="max-width: 75px;" alt="Product-img" />
                                        </a>
                                        <a href="javascript: void(0);" class="ms-2">
                                        <img src="assets/images/products/product-6.jpg" class="img-fluid img-thumbnail p-2" style="max-width: 75px;" alt="Product-img" />
                                        </a>
                                        <a href="javascript: void(0);" class="ms-2">
                                        <img src="assets/images/products/product-3.jpg" class="img-fluid img-thumbnail p-2" style="max-width: 75px;" alt="Product-img" />
                                        </a>
                                        </div> *@
                                    </div>
                                    <!-- end col -->
                                    <div class="col-lg-7">
                                        <form class="ps-lg-4">
                                            <!-- Product title -->
                                            <h3 class="mt-0">@Model.Name <a href="javascript: void(0);" class="text-muted"></a> </h3>
                                            <p class="mb-1">Автор - @Model.Author?.FullName</p>

                                            <!-- Product stock -->
                                            <div class="mt-3">
                                                @if (Model.IsPicked)
                                                {
                                                    <span class="badge bg-danger">На руках</span>
                                                }

                                                else
                                                {
                                                    <span class="badge bg-success">В библиотеке</span>
                                                }
                                            </div>

                                            <!-- Quantity -->
                                            @if (User.Identity.IsAuthenticated && userRole)
                                            {

                                                <div class="mt-4">
                                                    <h6 class="font-14">Quantity</h6>
                                                    <div class="d-flex">
                                                        @if (Model.IsPicked && Model.Reader.Id != readerId)
                                                        {
                                                            <span class="btn btn-info" @* asp-controller="Reader" asp-action="AddBookToReader" asp-route-readerId="@readerId" asp-route-bookId="@Model.Id" *@> Хочу почитать </span>
                                                        }
                                                        else if (Model.Reader != null && Model.Reader.Id == readerId)
                                                        {
                                                            <a class="btn btn-danger ms-2" asp-controller="Reader" asp-action="AddBookToLibrary" asp-route-readerId="@readerId" asp-route-bookId="@Model.Id">Вернуть</a>
                                                        }
                                                        else
                                                        {
                                                            <a class="btn btn-success ms-2" asp-controller="Reader" asp-action="AddBookToReader" asp-route-readerId="@readerId" asp-route-bookId="@Model.Id" method="post">Взять</a>
                                                        }
                                                    </div>
                                                </div>
                                            }

                                            <!-- Product description -->
                                            <div class="mt-4">
                                                <h6 class="font-14">Description:</h6>
                                                <p>Синопсис </p>
                                            </div>

                                            <!-- Product information -->
                                            <div class="mt-4">
                                                <div class="row">
                                                    <div class="col-md-4">
                                                        <h6 class="font-14">Дата публикации</h6>
                                                        <p class="text-sm lh-150">@Model.Publication</p>
                                                    </div>
                                                    <div class="col-md-4">
                                                        <h6 class="font-14">Количество страниц</h6>
                                                        <p class="text-sm lh-150">@Model.PageCount</p>
                                                    </div>
                                                    <div class="col-md-4">
                                                        <h6 class="font-14">Человек прочитали</h6>
                                                        <p class="text-sm lh-150">@Model.NumberOfReading</p>
                                                    </div>
                                                    <div class="col-md-4">
                                                        <h6 class="font-14">Расположение</h6>
                                                        <p class="text-sm lh-150">Cтелаж №@Model.BookCase.BookShelfId, @Model.BookCase.row полка, @Model.BookCase.column ячейка"</p>
                                                    </div>
                                                </div>
                                            </div>

                                        </form>
                                    </div> <!-- end col -->
                                </div> <!-- end row-->

                            </div> <!-- end card-body-->
                        </div> <!-- end card-->
                    </div> <!-- end col-->
                </div>
                <!-- end row-->

            </div> <!-- container -->

        </div> <!-- content -->

    </div>
    <!-- END wrapper -->
    @*     <!-- bundle -->
    <script src="assets/js/vendor.min.js"></script>
    <script src="assets/js/app.min.js"></script> *@

</body>